services:
  apibank_database:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/
    ports:
      - "5432:5432"
    env_file:
      - .env

  apibankapp:
    image: api_bank
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - apibank_database
    env_file:
      - .env

volumes:
  pgdata: