"""Transaction number is True

Revision ID: 06c9e241b568
Revises: 0347a42843ac
Create Date: 2026-07-15 12:14:34.689573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c9e241b568'
down_revision: Union[str, Sequence[str], None] = '0347a42843ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_transactions_transaction_number'), ['transaction_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_transactions_transaction_number'), type_='unique')

    # ### end Alembic commands ###
