"""Corrigindo campo balance

Revision ID: 56e40078ac56
Revises: 9dc38e74b746
Create Date: 2026-06-23 17:44:01.709642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e40078ac56'
down_revision: Union[str, Sequence[str], None] = '9dc38e74b746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Saldo', sa.Float(), server_default='0', nullable=False))
        batch_op.create_unique_constraint('uq_accounts_user', ['user'])
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint('uq_accounts_user', type_='unique')
        batch_op.drop_column('Saldo')

    # ### end Alembic commands ###
