"""Reestrutando tabela account

Revision ID: 81c4b050e9b1
Revises: ec8bf984750c
Create Date: 2026-06-23 21:48:09.527980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c4b050e9b1'
down_revision: Union[str, Sequence[str], None] = 'ec8bf984750c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_accounts_email', ['email'])
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_constraint('uq_accounts_email', type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
