"""Incrementando campos em Account table

Revision ID: 9dc38e74b746
Revises: 8408de46de9e
Create Date: 2026-06-23 17:07:24.075654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc38e74b746'
down_revision: Union[str, Sequence[str], None] = '8408de46de9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'user')
    # ### end Alembic commands ###
