"""Incrementando campos em Account table

Revision ID: 9dc38e74b746
Revises: 8408de46de9e
Create Date: 2026-06-23 17:07:24.075654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc38e74b746'
down_revision: Union[str, Sequence[str], None] = '8408de46de9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_accounts_user', ['user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.drop_constraint('uq_accounts_user', type_='unique')
        batch_op.drop_column('user')
    # ### end Alembic commands ###
