"""Corrigindo campo balance 2

Revision ID: ec8bf984750c
Revises: 56e40078ac56
Create Date: 2026-06-23 17:45:35.080738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8bf984750c'
down_revision: Union[str, Sequence[str], None] = '56e40078ac56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), server_default='0', nullable=False))
        batch_op.drop_column('Saldo')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Saldo', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
